### ISSUE TITLE
No such module 'CoinGecko' and WalletKit

### ISSUE THREAD

**Issue by akhilccrb** [breadwallet/breadwallet-ios#153]
**Xcode 11, I pulled out the source but getting an error.**

**Comment by acorscadden** [comment]
Please try using Xcode 11. It also sounds like you might be opening the .xcodeproj file instead of the .xcworkspace file.

**Comment by akhilccrb** [comment]
Am useing Xcode 11.3, am at xcworkspace

**Comment by acorscadden** [comment]
Ah, you probably need to update git submodules.

**Comment by akhilccrb** [comment]
https://github.com/breadwallet/CoinGecko
this package not found

**Comment by akhilccrb** [comment]
No such module 'BRCore'

**Comment by adamdahan** [comment]
Any updates here same thing for me... I am running on Apple Silicon

**Comment by ewerx** [comment]
You need to run `git submodule update --init --recursive` to fetch submodules.

**Comment by adamdahan** [comment]
@ewerx you keep saying that but it doesn't work. I know you are trying to help but actually try to diagnose the issue instead of dropping commands that don't do anything. 

This is what happens after you run **git submodule update --init --recursive**

Bosslife@Adams-Air-2 breadwallet-ios % git submodule update --init --recursive
Cloning into '/Users/Bosslife/Github/ios/breadwallet-ios/Modules/mobile-font'...
remote: Repository not found.
fatal: repository 'https://github.com/breadwallet/mobile-font.git/' not found
fatal: clone of 'https://github.com/breadwallet/mobile-font.git' into submodule path '/Users/Bosslife/Github/ios/breadwallet-ios/Modules/mobile-font' failed
Failed to clone 'Modules/mobile-font'. Retry scheduled
Cloning into '/Users/Bosslife/Github/ios/breadwallet-ios/Modules/mobile-font'...
remote: Repository not found.
fatal: repository 'https://github.com/breadwallet/mobile-font.git/' not found
fatal: clone of 'https://github.com/breadwallet/mobile-font.git' into submodule path '/Users/Bosslife/Github/ios/breadwallet-ios/Modules/mobile-font' failed
Failed to clone 'Modules/mobile-font' a second time, aborting
Bosslife@Adams-Air-2 breadwallet-ios % 

**SWIFT PROTOBUF NOT FOUND**
**MISSING PACKAGE PRODUCT WALLETKIT.**
